import RandomGeneratorClient from "./RandomGeneratorClient";
import { Metadata } from "next";
import { getTranslations, setRequestLocale } from 'next-intl/server';
import { locales } from '@/navigation';

export function generateStaticParams() {
    return locales.map((locale) => ({ locale }));
}

export const dynamic = 'force-static';
export const revalidate = false;

const baseUrl = 'https://teck-tani.com';

export async function generateMetadata(props: { params: Promise<{ locale: string }> }): Promise<Metadata> {
    const { locale } = await props.params;
    const t = await getTranslations({ locale, namespace: 'RandomGenerator.meta' });
    const isKo = locale === 'ko';
    const url = `${baseUrl}/${locale}/random-generator`;

    return {
        title: t('title'),
        description: t('description'),
        keywords: t('keywords'),
        alternates: {
            canonical: url,
            languages: {
                'ko': `${baseUrl}/ko/random-generator`,
                'en': `${baseUrl}/en/random-generator`,
                'x-default': `${baseUrl}/ko/random-generator`,
            },
        },
        openGraph: {
            title: t('ogTitle'),
            description: t('ogDescription'),
            url,
            siteName: 'Teck-Tani 웹도구',
            type: 'website',
            locale: isKo ? 'ko_KR' : 'en_US',
            alternateLocale: isKo ? 'en_US' : 'ko_KR',
        },
        twitter: {
            card: 'summary_large_image',
            title: t('ogTitle'),
            description: t('ogDescription'),
        },
        robots: {
            index: true,
            follow: true,
            googleBot: {
                index: true,
                follow: true,
                'max-video-preview': -1,
                'max-image-preview': 'large',
                'max-snippet': -1,
            },
        },
    };
}

function generateFaqSchema(locale: string) {
    const faqData = locale === 'ko' ? [
        {
            question: "랜덤 생성기는 어떤 기능이 있나요?",
            answer: "숫자(정수/소수), 이름(한국어/영어), 색상(HEX/RGB/HSL), 주사위(D4~D20), 동전 뒤집기, 순서 섞기(셔플), 팀 나누기, 가중치 추첨 등 8가지 랜덤 생성 기능을 제공합니다."
        },
        {
            question: "생성된 숫자는 진짜 랜덤인가요?",
            answer: "네, 브라우저의 Math.random() 함수를 사용하여 의사난수(pseudo-random number)를 생성합니다. 통계적 분석이나 보안 목적이 아닌 일반적인 용도에 충분히 랜덤합니다."
        },
        {
            question: "한국 이름은 어떻게 생성되나요?",
            answer: "한국의 대표적인 성 50개(김, 이, 박, 최 등)와 이름에 자주 사용되는 음절 60개를 조합하여 4만 가지 이상의 자연스러운 한국 이름을 랜덤으로 생성합니다. 1~2음절 이름이 무작위로 만들어집니다."
        },
        {
            question: "주사위 종류는 무엇이 있나요?",
            answer: "D4(4면), D6(6면), D8(8면), D10(10면), D12(12면), D20(20면) 등 TRPG에서 사용되는 6가지 주사위를 지원합니다. 최대 10개까지 동시에 굴릴 수 있습니다."
        },
        {
            question: "개인정보가 수집되나요?",
            answer: "아니요, 모든 랜덤 생성은 브라우저에서 처리되며 어떠한 데이터도 서버로 전송되지 않습니다. 생성 결과는 페이지를 닫으면 사라집니다."
        }
    ] : [
        {
            question: "What features does the random generator have?",
            answer: "It provides 8 random generation features: numbers (integer/decimal), names (Korean/English), colors (HEX/RGB/HSL), dice rolling (D4-D20), coin flipping, shuffle, team divider, and weighted random picker."
        },
        {
            question: "Are the generated numbers truly random?",
            answer: "Yes, the tool uses the browser's Math.random() function to generate pseudo-random numbers. They are sufficiently random for general purposes, though not for statistical analysis or security."
        },
        {
            question: "How are Korean names generated?",
            answer: "Korean names are generated by combining 50 common Korean surnames (Kim, Lee, Park, Choi, etc.) with 60 frequently used name syllables, enabling over 40,000 unique natural-sounding Korean names with 1-2 syllable given names."
        },
        {
            question: "What types of dice are available?",
            answer: "The tool supports D4 (4 sides), D6 (6 sides), D8 (8 sides), D10 (10 sides), D12 (12 sides), and D20 (20 sides) - all commonly used in TRPG games. You can roll up to 10 dice simultaneously."
        },
        {
            question: "Is any personal data collected?",
            answer: "No, all random generation happens in your browser and no data is sent to any server. Generated results disappear when you close the page."
        }
    ];

    return {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": faqData.map(item => ({
            "@type": "Question",
            "name": item.question,
            "acceptedAnswer": {
                "@type": "Answer",
                "text": item.answer
            }
        }))
    };
}

function generateHowToSchema(locale: string) {
    const isKo = locale === 'ko';

    return {
        "@context": "https://schema.org",
        "@type": "HowTo",
        "name": isKo ? "랜덤 생성기 사용 방법" : "How to Use the Random Generator",
        "description": isKo
            ? "온라인 랜덤 생성기를 사용하여 숫자, 이름, 색상, 주사위, 동전 등을 랜덤으로 생성하는 방법"
            : "How to generate random numbers, names, colors, dice rolls, and coin flips using the online random generator",
        "step": isKo ? [
            {
                "@type": "HowToStep",
                "name": "모드 선택",
                "text": "상단 탭에서 원하는 랜덤 생성 모드를 선택합니다: 숫자, 이름, 색상, 주사위, 동전, 셔플, 팀 나누기, 가중치 추첨."
            },
            {
                "@type": "HowToStep",
                "name": "옵션 설정",
                "text": "선택한 모드에 맞는 옵션을 설정합니다. 예: 숫자 범위, 이름 유형, 색상 개수, 주사위 면 수 등."
            },
            {
                "@type": "HowToStep",
                "name": "생성하기",
                "text": "생성 버튼을 클릭하여 랜덤 결과를 즉시 생성합니다."
            },
            {
                "@type": "HowToStep",
                "name": "결과 복사",
                "text": "생성된 결과를 클릭하거나 복사 버튼을 사용하여 클립보드에 복사합니다."
            }
        ] : [
            {
                "@type": "HowToStep",
                "name": "Select Mode",
                "text": "Choose from 8 random generation modes in the top tabs: Number, Name, Color, Dice, Coin, Shuffle, Teams, or Weighted Picker."
            },
            {
                "@type": "HowToStep",
                "name": "Configure Options",
                "text": "Set options for your selected mode. For example: number range, name type, color count, dice sides, etc."
            },
            {
                "@type": "HowToStep",
                "name": "Generate",
                "text": "Click the generate button to instantly create random results."
            },
            {
                "@type": "HowToStep",
                "name": "Copy Results",
                "text": "Click on the results or use the copy button to copy them to your clipboard."
            }
        ]
    };
}

function generateWebAppSchema(locale: string) {
    const isKo = locale === 'ko';

    return {
        "@context": "https://schema.org",
        "@type": "WebApplication",
        "name": isKo ? "랜덤 생성기" : "Random Generator",
        "description": isKo
            ? "숫자, 이름, 색상, 주사위, 동전 등 다양한 랜덤 생성 기능을 제공하는 무료 온라인 도구입니다."
            : "Free online tool providing various random generation features including numbers, names, colors, dice, and coin flips.",
        "url": `${baseUrl}/${locale}/random-generator`,
        "applicationCategory": "UtilitiesApplication",
        "operatingSystem": "Any",
        "offers": {
            "@type": "Offer",
            "price": "0",
            "priceCurrency": "KRW"
        },
        "featureList": isKo
            ? [
                "랜덤 숫자 생성 (정수/소수, 범위 지정, 다량 생성, 중복 없이)",
                "랜덤 이름 생성 (한국어/영어, 성 50개·음절 60개)",
                "랜덤 색상 생성 (HEX/RGB/HSL, 팔레트 4종)",
                "주사위 굴리기 (D4/D6/D8/D10/D12/D20, RPG 표기법 지원)",
                "동전 뒤집기 (앞면/뒷면, 히스토리 기록)",
                "순서 섞기 - Fisher-Yates 셔플 알고리즘",
                "팀 나누기 (균등 분배)",
                "가중치 추첨 (확률 가중치 설정)"
            ]
            : [
                "Random number generation (integer/decimal, custom range, bulk, no-duplicate mode)",
                "Random name generation (Korean/English, 50 surnames · 60 syllables)",
                "Random color generation (HEX/RGB/HSL, 4 palette modes)",
                "Dice rolling (D4/D6/D8/D10/D12/D20, RPG dice notation support)",
                "Coin flipping (heads/tails, flip history)",
                "Shuffle - Fisher-Yates algorithm",
                "Team divider (even distribution)",
                "Weighted random picker (probability weight control)"
            ],
        "browserRequirements": "Requires JavaScript. Requires HTML5.",
        "softwareVersion": "1.0"
    };
}

export default async function RandomGeneratorPage(props: { params: Promise<{ locale: string }> }) {
    const { locale } = await props.params;
    setRequestLocale(locale);
    const t = await getTranslations({ locale, namespace: 'RandomGenerator' });

    const faqSchema = generateFaqSchema(locale);
    const howToSchema = generateHowToSchema(locale);
    const webAppSchema = generateWebAppSchema(locale);

    const featureKeys = ["feat1", "feat2", "feat3", "feat4", "feat5", "feat6", "feat7", "feat8"] as const;
    const howtoKeys = ["step1", "step2", "step3", "step4"] as const;
    const usecaseKeys = ["uc1", "uc2", "uc3", "uc4", "uc5"] as const;
    const faqKeys = ["q1", "q2", "q3", "q4", "q5"] as const;

    return (
        <>
            <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
            />
            <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{ __html: JSON.stringify(howToSchema) }}
            />
            <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{ __html: JSON.stringify(webAppSchema) }}
            />

            <RandomGeneratorClient />

            <article className="seo-article">
                {/* 1. Description */}
                <section className="seo-section">
                    <h2 className="seo-section-title">{t("seo.description.title")}</h2>
                    <p className="seo-text">{t("seo.description.p1")}</p>
                    <p className="seo-text">{t("seo.description.p2")}</p>
                </section>
                {/* 2. Features */}
                <section className="seo-section">
                    <h2 className="seo-section-title">{t("seo.features.title")}</h2>
                    <div className="seo-card-grid">
                        {featureKeys.map((key) => (
                            <div key={key} className="seo-card">
                                <h3 className="seo-card-title">{t(`seo.features.list.${key}.title`)}</h3>
                                <p className="seo-card-desc">{t(`seo.features.list.${key}.desc`)}</p>
                            </div>
                        ))}
                    </div>
                </section>
                {/* 3. How to Use */}
                <section className="seo-section">
                    <h2 className="seo-section-title">{t("seo.howto.title")}</h2>
                    <ol className="seo-howto-list">
                        {howtoKeys.map((key) => (
                            <li key={key} dangerouslySetInnerHTML={{ __html: t.raw(`seo.howto.steps.${key}`) }} />
                        ))}
                    </ol>
                </section>
                {/* 4. Use Cases */}
                <section className="seo-section">
                    <h2 className="seo-section-title">{t("seo.usecases.title")}</h2>
                    <div className="seo-card-grid">
                        {usecaseKeys.map((key) => (
                            <div key={key} className="seo-card">
                                <h3 className="seo-card-title">{t(`seo.usecases.list.${key}.title`)}</h3>
                                <p className="seo-card-desc">{t(`seo.usecases.list.${key}.desc`)}</p>
                            </div>
                        ))}
                    </div>
                </section>
                {/* 5. FAQ */}
                <section className="seo-section">
                    <h2 className="seo-section-title">{t("seo.faq.title")}</h2>
                    {faqKeys.map((key) => (
                        <details key={key} className="seo-faq-item">
                            <summary>{t(`seo.faq.${key}.q`)}</summary>
                            <p>{t(`seo.faq.${key}.a`)}</p>
                        </details>
                    ))}
                </section>
                {/* 6. Privacy */}
                <section className="seo-section">
                    <h2 className="seo-section-title">{t("seo.privacy.title")}</h2>
                    <p className="seo-text">{t("seo.privacy.text")}</p>
                </section>
            </article>
        </>
    );
}
